.TH icm-agent Alpha "May 21, 2012"

.SH NAME
icm-agent \- Internet Connectivity Monitor

.SH SYNOPSIS
\fBicm-agent\fP

.SH DESCRIPTION
\fBicm-agent\fP can raise an alarm whenever such natural or deliberate shortages or blockages take place by leveraging a world wide Internet Connectivity Monitor.

.PP
With \fBicm-agent\fP, you can see the Internet Monitor.

.SH FILES
.TP
~/.icm-agent
Stores configuration settings for \fBicm-agent\fP.

.SH BUGS
Please report bugs at http://dev.umitproject.org/projects/desktop-agent/issues/new

.SH SEE ALSO
http://www.openmonitor.org

.SH AUTHORS
Adriano Monteiro Marques <adriano@umitproject.org>

Alan wang <wzj401@gmail.com>

João Medeiros <ignotus@umitproject.org>

Luis A. Bastiao Silva <luis.kop@gmail.com>

Rodolfo Carvalho <rodolfo@umitproject.org>

Narendran Thangarajan <narendran.thangarajan@gmail.com>

This manual page was written by Tianwei liu <liutianweidlut@gmail.com>.

