# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='report.proto',
  package='org.umit.icm.proto',
  serialized_pb='\n\x0creport.proto\x12\x12org.umit.icm.proto\"\xe7\x01\n\tICMReport\x12\x10\n\x08reportID\x18\x01 \x02(\x03\x12\x10\n\x08senderID\x18\x02 \x02(\x03\x12\x11\n\ttimestamp\x18\x03 \x02(\x03\x12\x0e\n\x06testID\x18\x04 \x02(\x05\x12\x13\n\x0bpassedNodes\x18\x05 \x03(\x0c\x12>\n\rwebsiteReport\x18\x64 \x03(\x0b\x32\'.org.umit.icm.proto.WebsiteReportDetail\x12>\n\rserviceReport\x18\x65 \x03(\x0b\x32\'.org.umit.icm.proto.ServiceReportDetail\"l\n\x13WebsiteReportDetail\x12\x12\n\nwebsiteURL\x18\x02 \x02(\t\x12\x12\n\nstatusCode\x18\x03 \x02(\x05\x12\x14\n\x0cresponseTime\x18\x04 \x01(\x01\x12\x11\n\tbandwidth\x18\x05 \x01(\x01*\x04\x08\n\x10\x64\"m\n\x13ServiceReportDetail\x12\x13\n\x0bserviceName\x18\x02 \x02(\t\x12\x12\n\nstatusCode\x18\x03 \x02(\x05\x12\x14\n\x0cresponseTime\x18\x04 \x01(\x01\x12\x11\n\tbandwidth\x18\x05 \x01(\x01*\x04\x08\n\x10\x64')




_ICMREPORT = descriptor.Descriptor(
  name='ICMReport',
  full_name='org.umit.icm.proto.ICMReport',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='reportID', full_name='org.umit.icm.proto.ICMReport.reportID', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='senderID', full_name='org.umit.icm.proto.ICMReport.senderID', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='timestamp', full_name='org.umit.icm.proto.ICMReport.timestamp', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='testID', full_name='org.umit.icm.proto.ICMReport.testID', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='passedNodes', full_name='org.umit.icm.proto.ICMReport.passedNodes', index=4,
      number=5, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='websiteReport', full_name='org.umit.icm.proto.ICMReport.websiteReport', index=5,
      number=100, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='serviceReport', full_name='org.umit.icm.proto.ICMReport.serviceReport', index=6,
      number=101, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=37,
  serialized_end=268,
)


_WEBSITEREPORTDETAIL = descriptor.Descriptor(
  name='WebsiteReportDetail',
  full_name='org.umit.icm.proto.WebsiteReportDetail',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='websiteURL', full_name='org.umit.icm.proto.WebsiteReportDetail.websiteURL', index=0,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='statusCode', full_name='org.umit.icm.proto.WebsiteReportDetail.statusCode', index=1,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='responseTime', full_name='org.umit.icm.proto.WebsiteReportDetail.responseTime', index=2,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='bandwidth', full_name='org.umit.icm.proto.WebsiteReportDetail.bandwidth', index=3,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=True,
  extension_ranges=[(10, 100), ],
  serialized_start=270,
  serialized_end=378,
)


_SERVICEREPORTDETAIL = descriptor.Descriptor(
  name='ServiceReportDetail',
  full_name='org.umit.icm.proto.ServiceReportDetail',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='serviceName', full_name='org.umit.icm.proto.ServiceReportDetail.serviceName', index=0,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='statusCode', full_name='org.umit.icm.proto.ServiceReportDetail.statusCode', index=1,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='responseTime', full_name='org.umit.icm.proto.ServiceReportDetail.responseTime', index=2,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='bandwidth', full_name='org.umit.icm.proto.ServiceReportDetail.bandwidth', index=3,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=True,
  extension_ranges=[(10, 100), ],
  serialized_start=380,
  serialized_end=489,
)

_ICMREPORT.fields_by_name['websiteReport'].message_type = _WEBSITEREPORTDETAIL
_ICMREPORT.fields_by_name['serviceReport'].message_type = _SERVICEREPORTDETAIL
DESCRIPTOR.message_types_by_name['ICMReport'] = _ICMREPORT
DESCRIPTOR.message_types_by_name['WebsiteReportDetail'] = _WEBSITEREPORTDETAIL
DESCRIPTOR.message_types_by_name['ServiceReportDetail'] = _SERVICEREPORTDETAIL

class ICMReport(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ICMREPORT
  
  # @@protoc_insertion_point(class_scope:org.umit.icm.proto.ICMReport)

class WebsiteReportDetail(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _WEBSITEREPORTDETAIL
  
  # @@protoc_insertion_point(class_scope:org.umit.icm.proto.WebsiteReportDetail)

class ServiceReportDetail(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SERVICEREPORTDETAIL
  
  # @@protoc_insertion_point(class_scope:org.umit.icm.proto.ServiceReportDetail)

# @@protoc_insertion_point(module_scope)
