# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='messages_ext.proto',
  package='',
  serialized_pb='\n\x12messages_ext.proto\"?\n\x08\x44iagnose\x12\x10\n\x08\x65xecType\x18\x01 \x02(\x05\x12\x10\n\x08\x63ronTime\x18\x02 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x03 \x02(\t\"4\n\x10\x44iagnoseResponse\x12\x10\n\x08\x65xecTime\x18\x01 \x02(\x05\x12\x0e\n\x06result\x18\x02 \x02(\t')




_DIAGNOSE = descriptor.Descriptor(
  name='Diagnose',
  full_name='Diagnose',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='execType', full_name='Diagnose.execType', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='cronTime', full_name='Diagnose.cronTime', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='command', full_name='Diagnose.command', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=22,
  serialized_end=85,
)


_DIAGNOSERESPONSE = descriptor.Descriptor(
  name='DiagnoseResponse',
  full_name='DiagnoseResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='execTime', full_name='DiagnoseResponse.execTime', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='result', full_name='DiagnoseResponse.result', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=87,
  serialized_end=139,
)

DESCRIPTOR.message_types_by_name['Diagnose'] = _DIAGNOSE
DESCRIPTOR.message_types_by_name['DiagnoseResponse'] = _DIAGNOSERESPONSE

class Diagnose(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DIAGNOSE
  
  # @@protoc_insertion_point(class_scope:Diagnose)

class DiagnoseResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DIAGNOSERESPONSE
  
  # @@protoc_insertion_point(class_scope:DiagnoseResponse)

# @@protoc_insertion_point(module_scope)
