install:
	g++ -std=gnu++0x -c asio_service.cc -o asio_service.cc.o
	g++ -std=gnu++0x -c crypto.cc -o crypto.cc.o
	g++ -std=gnu++0x -c log.cc -o log.cc.o
	g++ -std=gnu++0x -c rsa.cc -o rsa.cc.o
	g++ -std=gnu++0x -c safe_encrypt.pb.cc -o safe_encrypt.pb.cc.o