// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "safe_encrypt.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace maidsafe {
namespace rsa {

namespace {

const ::google::protobuf::Descriptor* SafeEncrypt_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SafeEncrypt_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_maidsafe_2fcommon_2fsafe_5fencrypt_2eproto() {
  protobuf_AddDesc_maidsafe_2fcommon_2fsafe_5fencrypt_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "maidsafe/common/safe_encrypt.proto");
  GOOGLE_CHECK(file != NULL);
  SafeEncrypt_descriptor_ = file->message_type(0);
  static const int SafeEncrypt_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SafeEncrypt, key_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SafeEncrypt, data_),
  };
  SafeEncrypt_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SafeEncrypt_descriptor_,
      SafeEncrypt::default_instance_,
      SafeEncrypt_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SafeEncrypt, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SafeEncrypt, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(SafeEncrypt));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_maidsafe_2fcommon_2fsafe_5fencrypt_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SafeEncrypt_descriptor_, &SafeEncrypt::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_maidsafe_2fcommon_2fsafe_5fencrypt_2eproto() {
  delete SafeEncrypt::default_instance_;
  delete SafeEncrypt_reflection_;
}

void protobuf_AddDesc_maidsafe_2fcommon_2fsafe_5fencrypt_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\"maidsafe/common/safe_encrypt.proto\022\014ma"
    "idsafe.rsa\"(\n\013SafeEncrypt\022\013\n\003key\030\001 \002(\014\022\014"
    "\n\004data\030\002 \002(\014", 92);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "maidsafe/common/safe_encrypt.proto", &protobuf_RegisterTypes);
  SafeEncrypt::default_instance_ = new SafeEncrypt();
  SafeEncrypt::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_maidsafe_2fcommon_2fsafe_5fencrypt_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_maidsafe_2fcommon_2fsafe_5fencrypt_2eproto {
  StaticDescriptorInitializer_maidsafe_2fcommon_2fsafe_5fencrypt_2eproto() {
    protobuf_AddDesc_maidsafe_2fcommon_2fsafe_5fencrypt_2eproto();
  }
} static_descriptor_initializer_maidsafe_2fcommon_2fsafe_5fencrypt_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int SafeEncrypt::kKeyFieldNumber;
const int SafeEncrypt::kDataFieldNumber;
#endif  // !_MSC_VER

SafeEncrypt::SafeEncrypt()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void SafeEncrypt::InitAsDefaultInstance() {
}

SafeEncrypt::SafeEncrypt(const SafeEncrypt& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void SafeEncrypt::SharedCtor() {
  _cached_size_ = 0;
  key_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  data_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

SafeEncrypt::~SafeEncrypt() {
  SharedDtor();
}

void SafeEncrypt::SharedDtor() {
  if (key_ != &::google::protobuf::internal::kEmptyString) {
    delete key_;
  }
  if (data_ != &::google::protobuf::internal::kEmptyString) {
    delete data_;
  }
  if (this != default_instance_) {
  }
}

void SafeEncrypt::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SafeEncrypt::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SafeEncrypt_descriptor_;
}

const SafeEncrypt& SafeEncrypt::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_maidsafe_2fcommon_2fsafe_5fencrypt_2eproto();  return *default_instance_;
}

SafeEncrypt* SafeEncrypt::default_instance_ = NULL;

SafeEncrypt* SafeEncrypt::New() const {
  return new SafeEncrypt;
}

void SafeEncrypt::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_key()) {
      if (key_ != &::google::protobuf::internal::kEmptyString) {
        key_->clear();
      }
    }
    if (has_data()) {
      if (data_ != &::google::protobuf::internal::kEmptyString) {
        data_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool SafeEncrypt::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required bytes key = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_key()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_data;
        break;
      }
      
      // required bytes data = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_data:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_data()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void SafeEncrypt::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required bytes key = 1;
  if (has_key()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      1, this->key(), output);
  }
  
  // required bytes data = 2;
  if (has_data()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      2, this->data(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* SafeEncrypt::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required bytes key = 1;
  if (has_key()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->key(), target);
  }
  
  // required bytes data = 2;
  if (has_data()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        2, this->data(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int SafeEncrypt::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required bytes key = 1;
    if (has_key()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->key());
    }
    
    // required bytes data = 2;
    if (has_data()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->data());
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SafeEncrypt::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const SafeEncrypt* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const SafeEncrypt*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void SafeEncrypt::MergeFrom(const SafeEncrypt& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_key()) {
      set_key(from.key());
    }
    if (from.has_data()) {
      set_data(from.data());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void SafeEncrypt::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SafeEncrypt::CopyFrom(const SafeEncrypt& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SafeEncrypt::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;
  
  return true;
}

void SafeEncrypt::Swap(SafeEncrypt* other) {
  if (other != this) {
    std::swap(key_, other->key_);
    std::swap(data_, other->data_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata SafeEncrypt::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SafeEncrypt_descriptor_;
  metadata.reflection = SafeEncrypt_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace rsa
}  // namespace maidsafe

// @@protoc_insertion_point(global_scope)
