#!/bin/sh
set -x
# Automatically added by dh_installmenu
if [ "$1" = "configure" ] && [ -x "`which update-menus 2>/dev/null`" ]; then
	update-menus
fi
# End automatically added section
# Automatically added by dh_pycentral
rm -f /var/lib/pycentral/icm-agent.pkgremove
if which pycentral >/dev/null 2>&1; then
	pycentral pkginstall icm-agent
	if grep -qs '^icm-agent$' /var/lib/pycentral/delayed-pkgs; then
		sed -i '/^icm-agent$/d' /var/lib/pycentral/delayed-pkgs
	fi
fi
# End automatically added section
sudo chmod -R 777 /usr/share/umit/icmagent
